trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'nodejs'
  imageTag: 'v1-test'
  imageRepository: 'mvnrepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPushJob
    displayName: 'Build and Push Docker Image'
    steps:

    - task: Docker@2
      inputs:
        repository: 'nodejs'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
        addPipelineData: false
        addBaseImageData: false

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker tag nodejs:$(Build.BuildId) mvnrepo.azurecr.io/nodejs:$(Build.BuildId)
          az acr login -n mvnrepo.azurecr.io -u mvnrepo -p wFzE/+c2VTXgp4bCqZjrBEfJ8bXC/LHNvxGb0z/5+1+ACRDP4yVJ 
          docker push mvnrepo.azurecr.io/nodejs:$(Build.BuildId)
          docker save -o /home/vsts/work/1/a/nodejs.tar mvnrepo.azurecr.io/nodejs:$(Build.BuildId)
      displayName: 'Docker Imagetag and push'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'docker-image'
        publishLocation: 'Container'