trigger:
- none

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TodoList-NodeJS-Backend-build # The name of the pipeline referenced by this pipeline resource.
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  displayName: 'Download Build ID Artifact'
  inputs:
    buildType: 'specific'
    project: 'cf7f8411-dfc9-4a44-bb3d-fdd7b65dd258'
    pipeline: '14'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)/'
    cleanDestinationFolder: true


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker load -i /home/vsts/work/1/a/docker-image/nodejs.tar

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Get the current image tag from the file
      export IMAGE_TAG=$(docker images mvnrepo.azurecr.io/nodejs --format "{{.Tag}}")
      echo "$IMAGE_TAG"
      # Specify the path to your Kubernetes deployment YAML file
      YAML_FILE="/home/vsts/work/1/s/deployment/deployment.yml"
      # Replace the image tag in the YAML file
      sed -i "s|image: mvnrepo.azurecr.io/nodejs:.*$|image: mvnrepo.azurecr.io/nodejs:${IMAGE_TAG}|g"  $YAML_FILE


- task: AzureCLI@2
  inputs:
    azureSubscription: 'to-my-k8s-portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script1.sh'


- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'to-my-k8s-portal'
    azureResourceGroup: 'cicd-mvn'
    kubernetesCluster: 'mvn-spring'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment/deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'to-my-k8s-portal'
    azureContainerRegistry: 'mvnrepo.azurecr.io'
    secretName: 'burhanuddin-acr-secret'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'to-my-k8s-portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script2.sh'
    addSpnToEnvironment: 
